services:
  drupal:
    image: drupal:9
    ports:
      - '8080:80'
    environment:
      DRUPAL_DATABASE_HOST: postgres
      DRUPAL_DATABASE_NAME: postgres
      DRUPAL_DATABASE_USER: postgres
      DRUPAL_DATABASE_PASSWORD: examplePassword
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: examplePassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  postgres-data:
